<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0XTjL12\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0XTjL12/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0XTjL12.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container0XTjL12\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container0XTjL12\appAppKernelDevDebugContainer([
    'container.build_hash' => '0XTjL12',
    'container.build_id' => 'f581af8c',
    'container.build_time' => 1718632615,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0XTjL12');
