<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRyKzjO0\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRyKzjO0/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRyKzjO0.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerRyKzjO0\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerRyKzjO0\appAppKernelProdContainer([
    'container.build_hash' => 'RyKzjO0',
    'container.build_id' => '1be4f578',
    'container.build_time' => 1718096561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRyKzjO0');
