<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSFuF010\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSFuF010/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerSFuF010.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerSFuF010\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerSFuF010\appAppKernelProdContainer([
    'container.build_hash' => 'SFuF010',
    'container.build_id' => '3d250d81',
    'container.build_time' => 1700675698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSFuF010');
