<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXbrTCS\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXbrTCS/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDXbrTCS.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDXbrTCS\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDXbrTCS\appAppKernelProdContainer([
    'container.build_hash' => 'DXbrTCS',
    'container.build_id' => '5dc4f8ea',
    'container.build_time' => 1700661322,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXbrTCS');
