<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDsZxaxu\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDsZxaxu/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDsZxaxu.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDsZxaxu\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDsZxaxu\appAppKernelProdContainer([
    'container.build_hash' => 'DsZxaxu',
    'container.build_id' => 'a6d829e2',
    'container.build_time' => 1718612360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDsZxaxu');
