<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPw9Msp\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPw9Msp/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPw9Msp.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPw9Msp\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerKPw9Msp\appAppKernelDevDebugContainer([
    'container.build_hash' => 'KPw9Msp',
    'container.build_id' => '5c90b405',
    'container.build_time' => 1718708980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPw9Msp');
