<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQJsJC8\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQJsJC8/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHQJsJC8.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHQJsJC8\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHQJsJC8\appAppKernelProdContainer([
    'container.build_hash' => 'HQJsJC8',
    'container.build_id' => '2000de97',
    'container.build_time' => 1718707613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQJsJC8');
