<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGsaVUQZ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGsaVUQZ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGsaVUQZ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGsaVUQZ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGsaVUQZ\appAppKernelProdContainer([
    'container.build_hash' => 'GsaVUQZ',
    'container.build_id' => '17d30c80',
    'container.build_time' => 1705335604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGsaVUQZ');
