<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSFtP6SF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSFtP6SF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerSFtP6SF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerSFtP6SF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerSFtP6SF\appAppKernelProdContainer([
    'container.build_hash' => 'SFtP6SF',
    'container.build_id' => '1a74c0e4',
    'container.build_time' => 1701946446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSFtP6SF');
