<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXE0BEQz\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXE0BEQz/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXE0BEQz.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXE0BEQz\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXE0BEQz\appAppKernelProdContainer([
    'container.build_hash' => 'XE0BEQz',
    'container.build_id' => 'b08db4b6',
    'container.build_time' => 1699293299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXE0BEQz');
