<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuMY+mccU2gVZQ6pnfBfH'."\n".'frKZEf9S9DwAsJjU/MggqZeFbvZBPAziO+ApA6VUlTRhqJhfycZZKU0H7xYTXNM7'."\n".'mrZU23x1rHB638zX2ZvkF54exx/vN0BmAseeT2/Nn1GyZ9uurHLm+TTDnaUALCkb'."\n".'is3CSarqFfeKy8RUNdJsfm7wXPU0P+pqy2j+QOBN3irU3eVnUSYZqiLQesyUs2AW'."\n".'yXVrJPhkX+AMPVNt4ychRtph4t+sF7eiCWm8khpBVczudKQkF8yCMQM3LKYj9AXz'."\n".'JZ9rRvVXUTpIxJ2KDl5RxLEmtPsZfZL8oK/nRzJA76f+xmI6nnfjE0Lw6oABiUKp'."\n".'MQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
