<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWaW4SYg\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWaW4SYg/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWaW4SYg.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWaW4SYg\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerWaW4SYg\appAppKernelDevDebugContainer([
    'container.build_hash' => 'WaW4SYg',
    'container.build_id' => '81e9df7d',
    'container.build_time' => 1717598342,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWaW4SYg');
