<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKZ4UdL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKZ4UdL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPKZ4UdL.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPKZ4UdL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPKZ4UdL\appAppKernelProdContainer([
    'container.build_hash' => 'PKZ4UdL',
    'container.build_id' => '6fec3a07',
    'container.build_time' => 1718899835,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKZ4UdL');
