<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerEEKUdii\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEEKUdii/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEEKUdii.legacy');
=======
if (\class_exists(\ContainerC2cG1VC\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2cG1VC/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2cG1VC.legacy');
>>>>>>> 18b6231d41890bd0c45eba5f4e6d67dbf23febde

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerEEKUdii\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerEEKUdii\appAppKernelDevDebugContainer([
    'container.build_hash' => 'EEKUdii',
    'container.build_id' => 'd214e660',
    'container.build_time' => 1700489074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEEKUdii');
=======
    \class_alias(\ContainerC2cG1VC\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerC2cG1VC\appAppKernelDevDebugContainer([
    'container.build_hash' => 'C2cG1VC',
    'container.build_id' => 'a3b389c8',
    'container.build_time' => 1699982189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2cG1VC');
>>>>>>> 18b6231d41890bd0c45eba5f4e6d67dbf23febde
