<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaKTdHO\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaKTdHO/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaKTdHO.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaKTdHO\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerNaKTdHO\appAppKernelDevDebugContainer([
    'container.build_hash' => 'NaKTdHO',
    'container.build_id' => '10b2870f',
    'container.build_time' => 1718900650,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaKTdHO');
